spring:
  application:
    name: app-consumer
  profiles:
    include: 8001
eureka:
  client:
    service-url:
      defaultZone:
                    http://localhost:8761/eureka,
                    http://localhost:8762/eureka,
                    http://localhost:8763/eureka
feign:
  hystrix:
    enabled: true
