server:
  port: 8761
eureka:
  instance:
    hostname: server1
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka,
                    http://localhost:8763/eureka